# T-test and correlation

In [1]:
# description:
# t-test is used on one continous feature, that is when we want to find if there is any change in the mean of the value wrt some
# other mean or something, now based on our comparison we will decide if our hypothesis is accepted or rejected..
# for hypothesis select or reject we will be writing a simple python code to see if it falls above the value 0.05
# if its less than 0.05 then we reject our null-hypothesis and accept alternate hypothesis

# t-test is one of the tests that compare the null and alternate hypothesis, there are lot more, this is used when the value we
# are considering is continous in nature
# t-test further categorized as one sample test and two sample test
# the one sample : uses one test data set
# you have to import it from scipy.stats import ttest_1samp...
# function ---- t_calc_value, p_calc_value = stats.ttest_1samp(age_sample, 30) ------- where age is the average we calc
# two sample : uses and compares aganist two samples (we use the data of weight of student if increased to similar mean or not)
# function ---- t_calc_value, p_calc_value = stats.ttest_ind(a=classAheight, b=classBheight, equal_var = False) //don't know equal_var

# there is an additional category called PAIRED P TEST , used to test how different samples from the same group are
# function ---- stats.ttest_rel(a=weighta, b=weightb)---------

# corellation is calculated as df.corr(), then sns.pairplot(df) to visualize

# additionl learned :
# stats module import : import scipy.stats as stats
# calculate the possion distribution 
# stats.poisson.rvs(loc= 18, mu = 35, size = 1500) -> gives a poisson distrubiton with min=18 max = 35 and total count = 1500


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [40]:
import scipy.stats as stats

In [33]:
ages = np.array(stats.poisson.rvs(loc=27, mu=35, size = 20))

In [19]:
ages

array([65, 59, 62, 56, 66, 65, 60, 55, 60, 70, 57, 72, 64, 58, 62, 71, 64,
       67, 68, 73])

In [34]:
from scipy.stats import ttest_1samp

In [35]:
np.average(ages)

61.45

In [36]:
t_test_val, p_val = ttest_1samp(ages, 61)
p_val

0.7536413758722798

In [62]:
# set my hypothesis if < .5 then not set true, else set false
def calc(p_val):
    if p_val < 0.05:
        print('alternate hypothesis selected')
    else:
        print('null hypothesis selected')

In [63]:
calc(p_val)

null hypothesis selected


## two sample ttest

In [51]:
childweight = stats.poisson.rvs(loc=27, mu =1, size= 10)

In [52]:
childweight

array([27, 28, 29, 27, 29, 29, 27, 28, 27, 28])

In [55]:
adultweight = stats.poisson.rvs(loc=57, mu = 1.5, size=10)

In [56]:
adultweight

array([59, 59, 58, 59, 60, 60, 59, 57, 58, 58])

In [57]:
# lets see the t_test between the adult value and child values
from scipy.stats import ttest_ind

In [60]:
t_result, p_result = ttest_ind(a= childweight, b= adultweight, equal_var= False)

In [64]:
calc(p_result)

alternate hypothesis selected


In [65]:
p_result

7.525475748886391e-24

## when you want to check how different groups are from the same

In [66]:
prev_weight = np.array([27, 28, 29, 27, 29, 29, 27, 28, 27, 28])

In [72]:
new_weight = [int(x) for x in prev_weight + stats.norm.rvs(scale = 5, loc = -1.25, size = 10)]

In [76]:
new_weight = np.array(new_weight)

In [77]:
new_weight.dtype

dtype('int32')

In [104]:
df1 = pd.DataFrame(prev_weight)
df2 = pd.DataFrame(new_weight)

In [105]:
df = pd.concat([df1, df2], axis =1)

In [109]:
df.columns = ['old_weight', 'new_weight']

In [110]:
df

old_weight  new_weight
0          27          19
1          28          28
2          29          30
3          27          33
4          29          22
5          29          26
6          27          24
7          28          27
8          27          28
9          28          26

In [111]:
# now lets find the ttest between the values of teh same table

In [112]:
_, p_val = stats.ttest_rel(a= df['old_weight'], b= df['new_weight'])

In [113]:
calc(p_val)

null hypothesis selected


In [114]:
p_val

0.2442155499217641